name: run_tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Install tree-datalad
      run: |
        echo "./tree-datalad" >> $GITHUB_PATH
        
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        conda install -c conda-forge datalad
        conda install pytest

    - name: Test with pytest
      run: |
        pytest

