name: run_tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Install tree-datalad
      run: |
        echo "./tree-datalad" >> $GITHUB_PATH
        
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        conda install -c conda-forge datalad
        conda install pytest

    - name: Test with pytest
      run: |
        $CONDA/bin/pytest

