name: run_tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    
    - name: Check out repo
      uses: actions/checkout@v3
      
    - name: Install tree-datalad
      run: |
        echo "$(pwd)" >> $GITHUB_PATH
        
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.9"
    
    - name: Install dependencies
      run: |
        conda install -c conda-forge datalad
        conda install pytest pytest-html
        
    - name: Configure git identity for DataLad
      run: |
        git config --global user.name "github runner"
        git config --global user.email "github@example.com"

    - name: Test with pytest
      run: |
        pytest --disable-warnings --html=tests/output/report.html
        
    - name: Archive test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests/output/*

