name: run_tests

on: pull_request

jobs:
  test:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        tree-version: [tree_1.6.0-1_amd64.deb,tree_1.7.0-3_amd64.deb,tree_1.7.0-5_amd64.deb,tree_1.8.0-1_amd64.deb,tree_2.0.2-1_amd64.deb]

    runs-on: ${{ matrix.os }}
    
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Check out repo
      uses: actions/checkout@v3

    - name: Install tree-datalad
      run: echo "$(pwd)" >> $GITHUB_PATH

    - name: Install tree on Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        tests/utils/install_tree_version.sh ${{ matrix.tree-version }}

    - name: Install tree on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install tree
        tree --version

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2

    - name: Install dependencies
      run: |
        conda install -c conda-forge datalad
        conda install pytest pytest-html
        
    - name: Configure git identity for DataLad
      run: |
        git config --global user.name "github runner"
        git config --global user.email "github@example.com"

    - name: Test with pytest
      run: pytest
        
    - name: Archive test results
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: tests/output/

